# Generated by Django 5.0.1 on 2024-02-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True)),
                ('health_points', models.IntegerField()),
                ('mana_points', models.IntegerField()),
                ('atk_points', models.FloatField()),
                ('matk_points', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LevelExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True)),
                ('experience_required', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('line_user_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.FloatField(default=1.0)),
                ('experience', models.FloatField(default=0.0)),
                ('health_points', models.FloatField(default=100.0)),
                ('mana_points', models.FloatField(default=50.0)),
            ],
        ),
    ]
